; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][version] = "1.3"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Modules
projects[date][version] = "2.6"

projects[entity][version] = "1.1"

projects[entityreference][version] = "1.0"

projects[features][version] = "2.0-rc1"

projects[fonticon][version] = "1.x-dev"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[metatag][version] = "1.0-beta7"

projects[pathauto][version] = "1.2"

projects[pushtape_admin][download][type] = "git"
projects[pushtape_admin][download][url] = "https://github.com/valkum/pushtape_admin.git"
projects[pushtape_admin][version] = "1.0"

projects[pushtape_discography][version] = "1.0-beta1"

projects[pushtape_events][download][type] = "git"
projects[pushtape_events][download][url] = "https://github.com/valkum/pushtape_events.git"
projects[pushtape_events][version] = "1.0"

projects[pushtape_news][version] = "1.0-beta1"

projects[pushtape_photos][version] = "1.0-beta1"

projects[pushtape_ui][version] = "1.0-beta1"

projects[social_links][version] = "1.x-dev"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

; Themes
projects[flux][version] = "1.0-beta1"

projects[framework][version] = "3.6"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[wsc_2013][download][type] = "git"
projects[wsc_2013][download][url] = "https://github.com/valkum/wsc_2013.git"
projects[wsc_2013][type] = "theme"
projects[wsc_2013][version] = "7.x-1.0"

