; This file was auto-generated by drush_make
core = 7.x
api = 2

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][version] = "1.4"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Modules
projects[date][version] = "2.7"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.0"

projects[features][version] = "2.0"

projects[colorbox][version] = "2.5"

projects[fonticon][version] = "1.x-dev"

projects[google_analytics][version] = "1.4"

projects[imce][version] = "1.8"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[link][version] = "1.2"

projects[l10n_update][version] = "1.0"

projects[metatag][version] = "1.0-beta9"

projects[multiupload_filefield_widget][version] = "1.13"

projects[multiupload_imagefield_widget][version] = "1.3"

projects[pathauto][version] = "1.2"

projects[plupload][version] = "1.6"

projects[pushtape_admin][type] = "module"
projects[pushtape_admin][download][type] = "git"
projects[pushtape_admin][download][url] = "https://github.com/valkum/pushtape_admin.git"

projects[pushtape_discography][version] = "1.0-beta1"

projects[pushtape_events][type] = "module"
projects[pushtape_events][download][type] = "git"
projects[pushtape_events][download][url] = "https://github.com/valkum/pushtape_events.git"

projects[pushtape_news][version] = "1.0-beta1"

projects[pushtape_audio][version] = "1.0-beta1"

projects[pushtape_photos][version] = "1.0-beta1"

projects[pushtape_ui][version] = "1.0-beta1"

projects[social_links][version] = "1.x-dev"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.2"

projects[views][version] = "3.7"

projects[workflow][version] = "2.2"

projects[xmlsitemap][version] = "2.0"

; Themes
projects[flux][version] = "1.0-beta1"

projects[framework][version] = "3.6"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[wsc_2013][download][type] = "git"
projects[wsc_2013][download][url] = "https://github.com/valkum/wsc_2013.git"
projects[wsc_2013][type] = "theme"
projects[wsc_2013][version] = "7.x-1.0"
